---
AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a simple Amazon Linux Instance and allow SSH connectivity.
Parameters:
  KeyName:
    Description: Default Key
    Type: AWS::EC2::KeyPair::KeyName
    Default: id_rsa_msa
Resources:
  SimpleInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      InstanceType: t2.micro
      ImageId: ami-0f7919c33c90f5b58