#Image is Ubuntu 18.04 in US-east-2

---
AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a simple Ubuntu 18.04 image with the Start Bootstrap Scrolling Nav template.
Parameters:
  KeyName:
    Description: Default Key
    Type: AWS::EC2::KeyPair::KeyName
    Default: id_rsa
Resources:
  SimpleInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      InstanceType: t2.micro
      ImageId: ami-0a63f96e85105c6d3
      UserData:
        Fn::Base64: 
         !Sub |
           #!/bin/bash -xe
           apt-get update
           apt-get upgrade -y
           apt-get install nginx -y
           apt-get install git -y
           git clone https://github.com/StartBootstrap/startbootstrap-scrolling-nav.git
           cp -r startbootstrap-scrolling-nav/. /var/www/html
           
           
