---
AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a simple Ubuntu 18.04 image with docker, docker-compose and Wordpress.
Parameters:
  KeyName:
    Description: Default Key
    Type: AWS::EC2::KeyPair::KeyName
    Default: id_rsa_msa
Resources:
  SimpleInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      InstanceType: t2.micro
      ImageId: ami-0a63f96e85105c6d3
      UserData:
        Fn::Base64: 
         !Sub |
           #!/bin/bash -xe
           apt-get update
           apt-get upgrade -y
           apt-get install docker.io -y
           apt-get install docker-compose -y
           apt-get install git -y
           git clone https://github.com/stevecosner/docker-compose-wp.git
           cd docker-compose-wp
           docker-compose up
           
